update fluentbit tests

diff --git a/test/testContainers/fluentbit/scope-test b/test/testContainers/fluentbit/scope-test
--- a/test/testContainers/fluentbit/scope-test
+++ b/test/testContainers/fluentbit/scope-test
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+
 ###################### Definitions ######################
 
 FAILED_TEST_LIST=""
@@ -28,276 +29,233 @@ endtest(){
     echo ""
 }
 
-wait_for_port() {
-    TIMEOUT=${2:-60}
-    while ! netstat -an | grep -w ${1} >/dev/null 2>&1; do
-        sleep 1
-        ((TIMEOUT=TIMEOUT-1))
-        if [ $TIMEOUT -le 0 ]; then
-            echo >&2 "warn: timed out waiting for port ${1} listener"
-            netstat -an | grep -w LISTEN >&2
-            return
-        fi
-    done
-    echo 1
-}
-
 wait_for_files() {
-    TIMEOUT=${2:-60}
+    TIMEOUT=${2:-30}
     while ! compgen -G "${1}" > /dev/null; do
         sleep 1
         ((TIMEOUT=TIMEOUT-1))
         if [ $TIMEOUT -le 0 ]; then
-            echo >&2 "warn: timed out waiting for port ${1} files"
-            ls -lRa /tmp/out >&2
+            echo >&2 "warn: timed out waiting for ${1} files"
+            ls -lRa /test_output/ >&2
             return
         fi
     done
     echo 1
 }
 
-###################### Setup ######################
-
-# Start LogStream
-# Logstream is setup to dump data sent to that source to NDJSON
-# files in ${DEST} named CriblOut-*.json.
-[ -z "$(pgrep cribl)" ] || { /opt/cribl/bin/cribl stop; sleep 5; }
-[ -d /tmp/out ] && rm -rf /tmp/out
-[ -d /tmp/out ] || mkdir /tmp/out
-/opt/cribl/bin/cribl start
-if [ ! "$(wait_for_port 10070)" ]; then
-    echo >&2 "error: LogStream failed to start; aborting test"
-    exit 1
-fi
-
-
 ###################### Tests ######################
 
-# Scope nginx with a variable nginx worker count
-# Use custom scope configuration to send only http events to a TCP socket
-# Use apache ab to send requests to nginx
-# Use fluentbit to relay events to a file
-# Assert on number of http events received
-fluentbit_tcp_file() {
-    starttest "Fluentbit_tcp->File_$1_Scope_$2_Requests"
-    DEST=/tmp/fluent.out_file
-    rm -rf ${DEST}
-    # start nginx with modified config
-    sed -i "s/worker_processes\ auto/worker_processes\ $1/" /etc/nginx/nginx.conf
-    SCOPE_HOME=/opt/test/conf_1 ldscope nginx
-    # sleep to allow nginx to start up
-    sleep 2
-    # start fluentbit
-    /opt/td-agent-bit/bin/td-agent-bit -i tcp -p "Port=9109" -p "Format=none" -o file -p "Format=plain" -p "Path=/tmp" -p "File=fluent.out_file" -d
-    # sleep to allow fluentbit to start
-    sleep 2
-    # run ab benchmark test
-    ab -n $2 -c 1 http://127.0.0.1/ > /dev/null 2>&1
-    # sleep to wait for ab to complete
-    sleep 15
-    if [ "$(wait_for_files "${DEST}")" ]; then
-        found=$(grep '\\"source\\":\\"http-req\\"' ${DEST} | wc -l)
-        if [ $found -eq $2 ] ; then 
-            echo "PASS: No missing http request events"
-        else
-            echo "FAIL: Missing http request events: expected: $2, got: $found, dropped: $(($2-found))"
-            ERR+=1
-        fi
-        found=$(grep '\\"source\\":\\"http-resp\\"' ${DEST} | wc -l)
-        if [ $found -eq $2 ] ; then 
-            echo "PASS: No missing http response events"
-        else
-            echo "FAIL: Missing http response events: expected: $2, got: $found, dropped: $(($2-found))"
-            ERR+=1
-        fi
-    else
-        echo "FAIL: no output files"
-        ERR+=1
-    fi
-    # kill processes
-    kill `pidof td-agent-bit`
-    nginx -s quit
-    # sleep to allow nginx and fluentbit to close (2+6 secs)
-    sleep 8
-    endtest
-}
-
-# Scope nginx with a variable nginx worker count
-# Use custom scope configuration to send only http events to a TCP socket
-# Use apache ab to send requests to nginx
-# Use fluentbit to relay events to logstream 
-# Assert on number of http events received
-fluentbit_tcp_logstream() {
-    starttest "Fluentbit_tcp->Logstream_$1_Scope_$2_Requests"
-    DEST=/tmp/out/tcpjson:in_tcp_json
-    rm -rf ${DEST}
-    # start nginx with modified config
-    sed -i "s/worker_processes\ auto/worker_processes\ $1/" /etc/nginx/nginx.conf
-    SCOPE_HOME=/opt/test/conf_1 ldscope nginx
-    # sleep to allow nginx to start up
-    sleep 2
-    # start fluentbit
-    /opt/td-agent-bit/bin/td-agent-bit -i tcp -p "Port=9109" -p "Format=none" -o tcp -p "Port=10070" -p "Format=json_lines" -p "json_date_key=false" -d
-    # sleep to allow fluentbit to start
-    sleep 2
-    # run ab benchmark test
-    ab -n $2 -c 1 http://127.0.0.1/ > /dev/null 2>&1
-    # sleep to wait for ab to complete
-    sleep 15
-    if [ "$(wait_for_files "${DEST}/CriblOut-*.json")" ]; then
-        found=$(grep '\\"source\\":\\"http-req\\"' ${DEST}/CriblOut-*.json | wc -l)
-        if [ $found -eq $2 ] ; then 
-            echo "PASS: No missing http request events"
-        else
-            echo "FAIL: Missing http request events: expected: $2, got: $found, dropped: $(($2-found))"
-            ERR+=1
-        fi
-        found=$(grep '\\"source\\":\\"http-resp\\"' ${DEST}/CriblOut-*.json | wc -l)
-        if [ $found -eq $2 ] ; then 
-            echo "PASS: No missing http response events"
-        else
-            echo "FAIL: Missing http response events: expected: $2, got: $found, dropped: $(($2-found))"
-            ERR+=1
-        fi
-    else
-        echo "FAIL: no output files"
-        ERR+=1
-    fi
-    # kill processes
-    kill `pidof td-agent-bit`
-    nginx -s quit
-    # sleep to allow nginx and fluentbit to close (2+6 secs)
-    sleep 8
-    endtest
-}
-
-# Scope nginx with a variable nginx worker count
+# Scope nginx
 # Use custom scope configuration to send only http events to a Unix Domain socket
 # Use apache ab to send requests to nginx
 # Use fluentbit to relay events to a file
 # Assert on number of http events received
-fluentbit_unix_file() {
-    starttest "Fluentbit_unix->File_$1_Scope_$2_Requests"
-    DEST=/tmp/fluent.out_file
-    rm -rf ${DEST}
-    # start nginx with modified config
-    sed -i "s/worker_processes\ auto/worker_processes\ $1/" /etc/nginx/nginx.conf
-    SCOPE_HOME=/opt/test/conf_2 ldscope nginx
-    # sleep to allow nginx to start up
-    sleep 2
-    # start fluentbit
-    /opt/td-agent-bit/bin/td-agent-bit -R /opt/test/fluentbit/parsers.conf -i syslog -p "Mode=unix_tcp" -p "Path=/tmp/abstest" -p "Parser=json" -o file -p "Format=plain" -p "Path=/tmp" -p "File=fluent.out_file" -d
-    # sleep to allow fluentbit to start
-    sleep 2
-    # change perms on unix socket file to allow non-root to write to it
-    chmod 666 /tmp/abstest
-    # run ab benchmark test
-    ab -n $2 -c 1 http://127.0.0.1/ > /dev/null 2>&1
-    # sleep to wait for ab to complete
-    sleep 15
-    if [ "$(wait_for_files "${DEST}")" ]; then
-        found=$(grep '"source":"http-req"' ${DEST} | wc -l)
-        if [ $found -eq $2 ] ; then 
+nginx_fluentbit_file() {
+    starttest "Nginx->Fluentbit->File_$1_Requests"
+
+    # launch services
+    export NGINX_ARGS='-c /test_configs/nginx_1_worker.conf'
+    export FLUENTBIT_ARGS='-c /test_configs/fluent-bit_to_file.conf -v'
+    docker-compose up -d --force-recreate --no-deps --build _service-fluentbit
+    docker-compose up -d --force-recreate --no-deps --build _service-nginx
+    sleep 5
+
+    # run ab
+    ab -c 1 -n $1 http://_service-nginx:80/
+    sleep 5 
+
+    # validate output
+    if [ "$(wait_for_files "/test_output/fluent.out")" ]; then
+        found=$(grep '"source":"http-req"' /test_output/fluent.out | wc -l)
+        if [ $found -eq $1 ] ; then 
             echo "PASS: No missing http request events"
         else
-            echo "FAIL: Missing http request events: expected: $2, got: $found, dropped: $(($2-found))"
+            echo "FAIL: Missing http request events: expected: $1, got: $found, dropped: $(($1-found))"
             ERR+=1
         fi
-        found=$(grep '"source":"http-resp"' ${DEST} | wc -l)
-        if [ $found -eq $2 ] ; then 
+        found=$(grep '"source":"http-resp"' /test_output/fluent.out | wc -l)
+        if [ $found -eq $1 ] ; then 
             echo "PASS: No missing http response events"
         else
-            echo "FAIL: Missing http response events: expected: $2, got: $found, dropped: $(($2-found))"
+            echo "FAIL: Missing http response events: expected: $1, got: $found, dropped: $(($1-found))"
             ERR+=1
         fi
     else
         echo "FAIL: no output files"
         ERR+=1
     fi
-    # kill processes
-    kill `pidof td-agent-bit`
-    nginx -s quit
-    # sleep to allow nginx and fluentbit to close (2+6 secs)
-    sleep 8
+
+    # terminate services
+    docker-compose kill
+
+    # cleanup
+    rm -rf /test_output/*
+
     endtest
 }
 
-# Scope nginx with a variable nginx worker count
+# Scope nginx
 # Use custom scope configuration to send only http events to a Unix Domain socket
 # Use apache ab to send requests to nginx
 # Use fluentbit to relay events to logstream
 # Assert on number of http events received
-fluentbit_unix_logstream() {
-    starttest "Fluentbit_unix->Logstream_$1_Scope_$2_Requests"
-    DEST=/tmp/out/tcpjson:in_tcp_json
-    rm -rf ${DEST}
-    # start nginx with modified config
-    sed -i "s/worker_processes\ auto/worker_processes\ $1/" /etc/nginx/nginx.conf
-    SCOPE_HOME=/opt/test/conf_2 ldscope nginx
-    # sleep to allow nginx to start up
-    sleep 2
-    # start fluentbit
-    /opt/td-agent-bit/bin/td-agent-bit -R /opt/test/fluentbit/parsers.conf -i syslog -p "Mode=unix_tcp" -p "Path=/tmp/abstest" -p "Parser=json" -o tcp -p "Port=10070" -p "Format=json_lines" -p "json_date_key=false" -d
-    # sleep to allow fluentbit to start
-    sleep 2
-    # change perms on unix socket file to allow non-root to write to it
-    chmod 666 /tmp/abstest
-    # run ab benchmark test
-    ab -n $2 -c 1 http://127.0.0.1/ > /dev/null 2>&1
-    # sleep to wait for ab to complete
-    sleep 15
-    if [ "$(wait_for_files "${DEST}/CriblOut-*.json")" ]; then
-        found=$(grep '"source":"http-req"' ${DEST}/CriblOut-*.json | wc -l)
-        if [ $found -eq $2 ] ; then 
+nginx_fluentbit_logstream() {
+    starttest "Nginx->Fluentbit->Logstream_$1_Requests"
+
+    # launch services
+    export NGINX_ARGS='-c /test_configs/nginx_1_worker.conf'
+    export FLUENTBIT_ARGS='-c /test_configs/fluent-bit.conf -v'
+    docker-compose up -d --force-recreate --no-deps --build _service-fluentbit
+    docker-compose up -d --force-recreate --no-deps --build _service-nginx
+    docker-compose up -d --force-recreate --no-deps --build _service-logstream
+    sleep 10
+
+    # run ab
+    ab -c 1 -n $1 http://_service-nginx:80/ 
+    sleep 20
+
+    # validate output
+    if [ "$(wait_for_files "/test_output/appscope:in_appscope/CriblOut-*.json")" ]; then
+        found=$(grep '"source":"http-req"' /test_output/appscope:in_appscope/CriblOut-*.json | wc -l)
+        if [ $found -eq $1 ] ; then 
             echo "PASS: No missing http request events"
         else
-            echo "FAIL: Missing http request events: expected: $2, got: $found, dropped: $(($2-found))"
+            echo "FAIL: Missing http request events: expected: $1, got: $found, dropped: $(($1-found))"
             ERR+=1
         fi
-        found=$(grep '"source":"http-resp"' ${DEST}/CriblOut-*.json | wc -l)
-        if [ $found -eq $2 ] ; then 
+        found=$(grep '"source":"http-resp"' /test_output/appscope:in_appscope/CriblOut-*.json | wc -l)
+        if [ $found -eq $1 ] ; then 
             echo "PASS: No missing http response events"
         else
-            echo "FAIL: Missing http response events: expected: $2, got: $found, dropped: $(($2-found))"
+            echo "FAIL: Missing http response events: expected: $1, got: $found, dropped: $(($1-found))"
             ERR+=1
         fi
     else
         echo "FAIL: no output files"
         ERR+=1
     fi
-    # kill processes
-    kill `pidof td-agent-bit`
-    nginx -s quit
-    # sleep to allow nginx and fluentbit to close (2+6 secs)
-    sleep 8
+
+    # terminate services
+    docker-compose kill
+
+    # cleanup
+    rm -rf /test_output/*
+
     endtest
 }
 
+# Scope 10 nginx workers
+# Use custom scope configuration to send only http events to a Unix Domain socket
+# Use apache ab to send requests to nginx
+# Use fluentbit to relay events to logstream
+# Assert on number of http events received
+multiple_nginx_fluentbit_logstream() {
+    starttest "Multiple-Nginx->Fluentbit->Logstream_$1_Requests"
 
-fluentbit_tcp_file 1 100
-fluentbit_tcp_file 1 1000
-fluentbit_tcp_file 1 10000
-fluentbit_tcp_file 10 100
-fluentbit_tcp_file 10 1000
-fluentbit_tcp_file 10 10000
-fluentbit_tcp_logstream 1 100
-fluentbit_tcp_logstream 1 1000
-fluentbit_tcp_logstream 1 10000
-fluentbit_tcp_logstream 10 100
-fluentbit_tcp_logstream 10 1000
-fluentbit_tcp_logstream 10 10000
-fluentbit_unix_file 1 100
-fluentbit_unix_file 1 1000
-fluentbit_unix_file 1 10000
-fluentbit_unix_file 10 100
-fluentbit_unix_file 10 1000
-fluentbit_unix_file 10 10000
-fluentbit_unix_logstream 1 100
-fluentbit_unix_logstream 1 1000
-fluentbit_unix_logstream 1 10000
-fluentbit_unix_logstream 10 100
-fluentbit_unix_logstream 10 1000
-fluentbit_unix_logstream 10 10000
+    # launch services
+    export NGINX_ARGS='-c /test_configs/nginx.conf'
+    export FLUENTBIT_ARGS='-c /test_configs/fluent-bit.conf -v'
+    docker-compose up -d --force-recreate --no-deps --build _service-fluentbit
+    docker-compose up -d --force-recreate --no-deps --build _service-nginx
+    docker-compose up -d --force-recreate --no-deps --build _service-logstream
+    sleep 10
+
+    # run ab
+    ab -c 1 -n $1 http://_service-nginx:80/ 
+    sleep 20
+
+    # validate output
+    if [ "$(wait_for_files "/test_output/appscope:in_appscope/CriblOut-*.json")" ]; then
+        found=$(grep '"source":"http-req"' /test_output/appscope:in_appscope/CriblOut-*.json | wc -l)
+        if [ $found -eq $1 ] ; then 
+            echo "PASS: No missing http request events"
+        else
+            echo "FAIL: Missing http request events: expected: $1, got: $found, dropped: $(($1-found))"
+            ERR+=1
+        fi
+        found=$(grep '"source":"http-resp"' /test_output/appscope:in_appscope/CriblOut-*.json | wc -l)
+        if [ $found -eq $1 ] ; then 
+            echo "PASS: No missing http response events"
+        else
+            echo "FAIL: Missing http response events: expected: $1, got: $found, dropped: $(($1-found))"
+            ERR+=1
+        fi
+    else
+        echo "FAIL: no output files"
+        ERR+=1
+    fi
+
+    # terminate services
+    docker-compose kill
+
+    # cleanup
+    rm -rf /test_output/*
+
+    endtest
+}
+
+# Scope nginx
+# Use custom scope configuration to send only http events to a Unix Domain socket
+# Use apache ab to send requests to nginx
+# Use fluentbit to relay events to logstream (Multiple fluentbit inputs)
+# Assert on number of http events received
+nginx_multiple_fluentbit_logstream() {
+    starttest "Nginx->Multiple_Fluentbit->Logstream_$1_Requests"
+
+    # launch services
+    export NGINX_ARGS='-c /test_configs/nginx_1_worker.conf'
+    export FLUENTBIT_ARGS='-c /test_configs/fluent-bit_multiple_inputs.conf -v'
+    docker-compose up -d --force-recreate --no-deps --build _service-fluentbit
+    docker-compose up -d --force-recreate --no-deps --build _service-nginx
+    docker-compose up -d --force-recreate --no-deps --build _service-logstream
+    sleep 10
+
+    # run ab
+    ab -c 1 -n $1 http://_service-nginx:80/ 
+    sleep 20
+
+    # validate output
+    if [ "$(wait_for_files "/test_output/appscope:in_appscope/CriblOut-*.json")" ]; then
+        found=$(grep '"source":"http-req"' /test_output/appscope:in_appscope/CriblOut-*.json | wc -l)
+        if [ $found -eq $1 ] ; then 
+            echo "PASS: No missing http request events"
+        else
+            echo "FAIL: Missing http request events: expected: $1, got: $found, dropped: $(($1-found))"
+            ERR+=1
+        fi
+        found=$(grep '"source":"http-resp"' /test_output/appscope:in_appscope/CriblOut-*.json | wc -l)
+        if [ $found -eq $1 ] ; then 
+            echo "PASS: No missing http response events"
+        else
+            echo "FAIL: Missing http response events: expected: $1, got: $found, dropped: $(($1-found))"
+            ERR+=1
+        fi
+    else
+        echo "FAIL: no output files"
+        ERR+=1
+    fi
+
+    # terminate services
+    docker-compose kill
+
+    # cleanup
+    rm -rf /test_output/*
+
+    endtest
+}
+
+#nginx_fluentbit_file 100
+#nginx_fluentbit_file 1000
+#nginx_fluentbit_file 10000
+#nginx_fluentbit_logstream 100
+#nginx_fluentbit_logstream 1000
+#nginx_fluentbit_logstream 10000
+#multiple_nginx_fluentbit_logstream 100
+#multiple_nginx_fluentbit_logstream 1000
+#multiple_nginx_fluentbit_logstream 10000
+nginx_multiple_fluentbit_logstream 100
+#nginx_multiple_fluentbit_logstream 1000
+#nginx_multiple_fluentbit_logstream 10000
 
 
 ###################### Summary ######################
